### ISSUE TITLE
layer sorting is incorrect

### ISSUE THREAD

**Issue by Megabalta** [GlyphXTools/particle-editor#2]
Particle Editor 1.4
Build date: Jun 15 2008
"v1.4:	Fixed a bug with particle system orientation. Orientation is now consistent with the Alo Viewer	(2008/06/15)"

Particle system orientation is still not consistent with the Alo Viewer or the game. It's reversed. Tested on Windows 7-10 systems (DX11+).

![emitter_orientation](https://user-images.githubusercontent.com/29461825/27191773-28b7f06e-51f9-11e7-8863-a665ae887005.jpg)

**Comment by Shimrra** [comment]
@MikeLankamp Do you still have the fixed code lying around? Apparently, the particle editor uploaded is an older version.

**Comment by MikeLankamp** [comment]
@Shimrra, why do you think it's an older version? This is the latest source code as I have it.

**Comment by Shimrra** [comment]
@MikeLankamp towards @Megabalta there are a couple of things in the current compiled version, that are fixed towards the changelog on modtools, e.g.

> v1.4:	Fixed a bug with particle system orientation. Orientation is now consistent with the Alo Viewer

Haven't confirmed myself though.

**Comment by Megabalta** [comment]
I've just tested the above problem both on the old /v1.4 Build date: Jun 15 2008/ and the new /v1.5 (I could only test the 32 bit version, the 64 bit version won't start at all on win10 somehow, no error message, just won't do anything, not even with compatibility troubleshooting) Build date: Jun 17 2017/ versions. 

The problem is sadly still there (never mind the lack of textures).

![v1 5bug](https://user-images.githubusercontent.com/29461825/27254509-fc65fc58-5389-11e7-9fcd-4d172058e740.JPG)

**Comment by MikeLankamp** [comment]
I just fixed the missing icons (I noticed that as well). Unfortunately I can't see your emitter settings. Can you please specify exactly how you create your emitters, or even better, zip up the saved particle file and attach it to this issue?

The 64-bit version starts for me (I'm on Windows 10 as well); I did get a warning about running a downloaded executable, but there's usually a way to click "continue" or similar. If it really doesn't work for you, can you please create a new issue for that with all the information (i.e. what *does* happen)?

**Comment by Megabalta** [comment]
You'll find the particle file (PE_AWINGENGINES.alo) and the model file (Rv_awing.alo) in the zip.
Open particle file in the particle editor, open model file in the alo viewer, look at the particles cyan and red emitters, which one is in the front. This is a mere visual problem in the particle editors playback window, it plays the particles emitter layout in reverse, which makes creating particles really hard, due to the need to always use the alo viewer/map editor to see how the particle looks like in the game.

[test_particle.zip](https://github.com/GlyphXTools/particle-editor/files/1082692/test_particle.zip)

I don't think the child emitter issue [#3](https://github.com/GlyphXTools/particle-editor/issues/3) is the same problem as this, since that's occuring ingame (it's about the relative positions of child-parent emitters), thus is not a visual problem of the particle editors playback window. I'll create a separate an issue for that if I can't solve it with multiple child emitters now that they work.

(I won't create an issue for the 64-bit version, since sadly I can't tell more: I press start on the 64-bit version, press continue in the windows warning, mouse cursor changes to loading cursor, then reverts back to normal cursor, nothing happens, I'm sorry I can't help with that any further)
