### ISSUE TITLE
Child emitters won't show as bursts

### ISSUE THREAD

**Issue by Megabalta** [GlyphXTools/particle-editor#4]
Child emitters won't show in game if their Generation is set to Bursts, although the particle editor shows them perfectly when previewing. Otherwise they work wonderfully, no more crashes.

/Thank you for fixing the orientation problem, works perfectly./

**Comment by MikeLankamp** [comment]
Unfortunately this is not a bug in the particle editor as such. I just checked the game's behavior and it simply does not support child (lifetime) emitters with burst mode. Only continuous. The editor must be fixed to disallow burst particles for child (lifetime) emitters.
