### ISSUE TITLE
Generation - continuous stream

### ISSUE THREAD

**Issue by Megabalta** [GlyphXTools/particle-editor#6]
Would it be possible to set Generation - continuous stream to Particles/minute or Particles/100 seconds instead of Particles/second? 
The 1 second time frame is too narrow to regulate how many emitters are showing up at a time, since most emitters playtime is longer than 1 seconds. This would allow a workaround for the child emitters not being able to use bursts mode.

**Comment by MikeLankamp** [comment]
Unfortunately that is not possible since the GlyphX file format stores "particles/second" as an integer. I can't store e.g. 0.5 if you were to input "30 particles/minute".
